name: business_card
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - images/

  fonts:
  - family: ubuntu
    fonts:
     - asset: fonts/Ubuntu-BoldItalic.ttf

  - family: sourceSansPro
    fonts:
     - asset: fonts/sourceSansPro-SemiBold.ttf

  - family: cinzel
    fonts:
     - asset: fonts/Cinzel-VariableFont_wght.ttf

  - family: solway
    fonts:
     - asset: fonts/Solway-Bold.ttf


